import Link from 'next/link';
import AdminPageHeader from '@/components/admin/AdminPageHeader';
import AuthNotice from '@/components/auth/AuthNotice';
import { requireAdmin } from '@/lib/auth';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { updateAssociationStatus } from '../actions';

type Association = { id: string; slug: string; name: string; city: string | null; email: string; status: string; created_at: string; members: { count: number }[]; tournaments: { count: number }[] };
export default async function AdminAssociationsPage({ searchParams }: { searchParams: Promise<{ erreur?: string; message?: string }> }) {
  const [, params] = await Promise.all([requireAdmin(), searchParams]); const supabase = await createServerSupabaseClient();
  const { data, error } = await supabase.from('associations').select('id, slug, name, city, email, status, created_at, members:association_members(count), tournaments(count)').is('deleted_at', null).order('created_at', { ascending: false });
  const associations = (data ?? []) as unknown as Association[];
  return <section className="px-4 py-10"><div className="mx-auto max-w-7xl"><AdminPageHeader eyebrow="Administration" title="Associations" description="Validation, suspension et vue d’ensemble des gestionnaires et tournois." /><AuthNotice error={params.erreur ?? error?.message} message={params.message} /><div className="mt-7 grid gap-4">{associations.map((association) => <article key={association.id} className="rounded-2xl border border-ink-200 bg-white p-5 shadow-soft"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><Link href={`/admin/associations/${association.id}`} className="font-display text-xl font-semibold hover:text-reunion-blue">{association.name}</Link><p className="mt-1 text-sm text-ink-500">{association.city ?? 'Commune inconnue'} · {association.email}</p><p className="mt-2 text-xs text-ink-400">{association.members?.[0]?.count ?? 0} membre(s) · {association.tournaments?.[0]?.count ?? 0} tournoi(s) · {association.status}</p></div><form action={updateAssociationStatus} className="flex flex-wrap gap-2"><input type="hidden" name="association_id" value={association.id} /><button name="status" value="approved" className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approuver</button><button name="status" value="rejected" className="rounded-lg border border-ink-200 px-3 py-2 text-xs">Refuser</button><button name="status" value="suspended" className="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-700">Suspendre</button><button name="status" value="pending" className="rounded-lg border border-blue-200 px-3 py-2 text-xs text-blue-700">Réactiver</button></form></div></article>)}{!associations.length && <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-ink-500">Aucune association.</p>}</div></div></section>;
}
