import Link from 'next/link';
import { ArrowLeft, UserPlus, UsersRound } from 'lucide-react';
import AuthNotice from '@/components/auth/AuthNotice';
import ProfileAvatar from '@/components/profile/ProfileAvatar';
import { requireIdentity } from '@/lib/auth';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { addAssociationMember, removeAssociationMember, updateAssociationMemberRole } from '../../actions';

type Member = { id: string; role: 'owner' | 'admin' | 'member'; user_id: string; profiles: { username: string; first_name: string | null; last_name: string | null; avatar_path: string | null } | { username: string; first_name: string | null; last_name: string | null; avatar_path: string | null }[] | null };

export default async function AssociationMembersPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ q?: string; erreur?: string; message?: string }> }) {
  const [{ id }, query, identity] = await Promise.all([params, searchParams, requireIdentity()]);
  const supabase = await createServerSupabaseClient();
  const { data: ownMembership } = await supabase.from('association_members').select('role, associations(name)').eq('association_id', id).eq('user_id', identity.id).eq('status', 'active').in('role', ['owner', 'admin']).maybeSingle();
  if (!ownMembership) return <section className="px-4 py-12 text-center"><h1 className="font-display text-2xl font-semibold">Accès refusé</h1><Link href="/mon-association" className="mt-4 inline-block text-sm underline">Retour</Link></section>;
  const [{ data: members }, searchResult] = await Promise.all([
    supabase.from('association_members').select('id, role, user_id, profiles(username, first_name, last_name, avatar_path)').eq('association_id', id).eq('status', 'active').order('created_at'),
    query.q && query.q.trim().length >= 2 ? supabase.from('profiles').select('id, username, first_name, last_name, avatar_path, club_name').eq('status', 'active').is('deleted_at', null).or(`username.ilike.%${query.q.replace(/[%_,().]/g, ' ')}%,first_name.ilike.%${query.q.replace(/[%_,().]/g, ' ')}%,last_name.ilike.%${query.q.replace(/[%_,().]/g, ' ')}%`).limit(8) : Promise.resolve({ data: [] }),
  ]);
  const associationValue = ownMembership.associations as { name: string } | { name: string }[] | null;
  const association = Array.isArray(associationValue) ? associationValue[0] : associationValue;
  const ownRole = ownMembership.role;

  return <section className="px-4 py-8 sm:py-12"><div className="mx-auto max-w-4xl"><Link href="/mon-association" className="inline-flex items-center gap-2 text-sm text-ink-500"><ArrowLeft className="h-4 w-4" /> Mon association</Link><div className="mt-6 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-reunion-blue">{association?.name}</p><h1 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Membres et responsables</h1></div><UsersRound className="h-8 w-8 text-ink-300" /></div><div className="mt-5"><AuthNotice error={query.erreur} message={query.message} /></div>
    <section className="mt-5 rounded-3xl border border-ink-200 bg-white p-5 shadow-soft sm:p-6"><h2 className="flex items-center gap-2 font-display text-xl font-semibold"><UserPlus className="h-5 w-5" /> Ajouter un utilisateur</h2><form className="mt-4 flex gap-2"><input name="q" defaultValue={query.q} placeholder="Rechercher un pseudo ou un nom" className="min-w-0 flex-1 rounded-xl border border-ink-200 px-4 py-3 text-base" /><button className="rounded-xl bg-ink-950 px-4 py-3 text-sm font-semibold text-white">Rechercher</button></form>{searchResult.data?.length ? <div className="mt-4 space-y-2">{searchResult.data.map((profile) => <form action={addAssociationMember} key={profile.id} className="flex flex-wrap items-center gap-3 rounded-2xl bg-ink-50 p-3"><input type="hidden" name="association_id" value={id} /><input type="hidden" name="username" value={profile.username} /><ProfileAvatar username={profile.username} avatarPath={profile.avatar_path} /><span className="min-w-32 flex-1"><strong className="block text-sm">@{profile.username}</strong><span className="text-xs text-ink-400">{[profile.first_name, profile.last_name, profile.club_name].filter(Boolean).join(' · ')}</span></span><select name="role" className="rounded-xl border border-ink-200 bg-white px-3 py-2 text-sm"><option value="admin">Responsable</option><option value="member">Membre</option></select><button className="rounded-xl bg-reunion-blue px-3 py-2 text-sm font-semibold text-white">Ajouter</button></form>)}</div> : query.q && <p className="mt-4 text-sm text-ink-400">Aucun résultat.</p>}</section>
    <section className="mt-6 space-y-3">{(members as unknown as Member[] | null)?.map((membership) => { const profile = Array.isArray(membership.profiles) ? membership.profiles[0] : membership.profiles; if (!profile) return null; return <article key={membership.id} className="flex flex-wrap items-center gap-3 rounded-2xl border border-ink-200 bg-white p-4"><ProfileAvatar username={profile.username} avatarPath={profile.avatar_path} /><span className="min-w-36 flex-1"><Link href={`/joueurs/${profile.username}`} className="font-semibold hover:underline">@{profile.username}</Link><span className="block text-xs text-ink-400">{[profile.first_name, profile.last_name].filter(Boolean).join(' ')}</span></span><form action={updateAssociationMemberRole} className="flex gap-2"><input type="hidden" name="association_id" value={id} /><input type="hidden" name="membership_id" value={membership.id} /><select name="role" defaultValue={membership.role} disabled={ownRole !== 'owner' && membership.role === 'owner'} className="rounded-xl border border-ink-200 bg-white px-3 py-2 text-sm"><option value="owner">Propriétaire</option><option value="admin">Responsable</option><option value="member">Membre</option></select><button className="rounded-xl border border-ink-200 px-3 py-2 text-xs font-semibold">Modifier</button></form><form action={removeAssociationMember}><input type="hidden" name="association_id" value={id} /><input type="hidden" name="membership_id" value={membership.id} /><button className="rounded-xl px-3 py-2 text-xs font-semibold text-red-600 hover:bg-red-50">Retirer</button></form></article>; })}</section>
  </div></section>;
}
