import Link from 'next/link';
import { ArrowLeft, ImagePlus } from 'lucide-react';
import AuthNotice from '@/components/auth/AuthNotice';
import OptimizedMediaPicker from '@/components/media/OptimizedMediaPicker';
import { requireIdentity } from '@/lib/auth';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { createTournament } from '../actions';
import PendingSubmitButton from '@/components/forms/PendingSubmitButton';

type Membership = { association: { id: string; name: string } | { id: string; name: string }[] | null };

export default async function NewTournamentPage({ searchParams }: { searchParams: Promise<{ erreur?: string }> }) {
  const [identity, params] = await Promise.all([requireIdentity('/connexion?retour=/mes-tournois/nouveau'), searchParams]);
  const supabase = await createServerSupabaseClient();
  const { data } = await supabase.from('association_members').select('association:associations!inner(id, name)').eq('user_id', identity.id).eq('status', 'active').in('role', ['owner', 'admin']).eq('associations.status', 'approved');
  const memberships = (data ?? []) as unknown as Membership[];
  const associations = memberships.map((entry) => Array.isArray(entry.association) ? entry.association[0] : entry.association).filter((item): item is { id: string; name: string } => Boolean(item));
  const creationToken = crypto.randomUUID();
  if (!associations.length) return <section className="px-4 py-16"><div className="mx-auto max-w-xl rounded-3xl border border-ink-200 bg-white p-8 text-center shadow-card"><ImagePlus className="mx-auto h-9 w-9 text-ink-300" /><h1 className="mt-4 font-display text-2xl font-semibold">Validation nécessaire</h1><p className="mt-2 text-sm leading-6 text-ink-500">Une association approuvée par VolleyPéi est nécessaire pour créer un tournoi.</p><Link href="/mon-association" className="mt-5 inline-flex rounded-xl bg-ink-950 px-5 py-3 text-sm font-semibold text-white">Voir mon association</Link></div></section>;

  return <section className="px-4 py-8 sm:py-14"><div className="mx-auto max-w-3xl"><Link href="/mes-tournois" className="inline-flex items-center gap-2 text-sm text-ink-500"><ArrowLeft className="h-4 w-4" /> Mes tournois</Link><p className="mt-7 text-xs font-semibold uppercase tracking-[0.18em] text-reunion-blue">Espace association</p><h1 className="mt-3 font-display text-3xl font-semibold sm:text-5xl">Créer un tournoi</h1><p className="mt-3 text-sm leading-6 text-ink-500">Les champs marqués « obligatoire » sont les seuls nécessaires. Les autres peuvent rester vides.</p><div className="mt-8 rounded-3xl border border-ink-200 bg-white p-6 shadow-card sm:p-8"><AuthNotice error={params.erreur} /><form action={createTournament} className="space-y-6">
    <input type="hidden" name="creation_token" value={creationToken} /><label className="block text-sm font-medium">Association<select name="association_id" required className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3">{associations.map((association) => <option key={association.id} value={association.id}>{association.name}</option>)}</select></label>
    <div><p className="mb-2 text-sm font-medium">Affiche optimisée <span className="text-red-600">* obligatoire</span></p><OptimizedMediaPicker usage="poster" required inputName="poster_media_id" /></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium">Nom du tournoi<input name="name" required maxLength={150} className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Date<input name="date" type="date" required className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Heure<input name="time" type="time" required className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Discipline<select name="type" required className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3"><option value="">Choisir</option>{['Beach volley','Volley indoor','Green volley','Officiel LRVB','Sparing','Loisirs'].map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-medium">Nombre d’équipes prévu<input name="players_count" type="number" min={1} required className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Nom du lieu<input name="location" required placeholder="Ex. Gymnase de Plateau Caillou" className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Commune<input name="city" required placeholder="Ex. Saint-Paul" className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium sm:col-span-2">Adresse <span className="font-normal text-ink-400">(facultatif)</span><input name="address" placeholder="Saisie manuelle" className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium sm:col-span-2">Format<input name="format" placeholder="2×2 mixte, 4×4…" className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label></div>
    <label className="block text-sm font-medium">Description <span className="font-normal text-ink-400">(facultatif)</span><textarea name="description" rows={5} maxLength={5000} className="mt-2 w-full resize-none rounded-xl border border-ink-200 px-4 py-3" /></label><label className="block text-sm font-medium">Informations complémentaires <span className="font-normal text-ink-400">(facultatif)</span><textarea name="additional_info" rows={3} maxLength={2000} className="mt-2 w-full resize-none rounded-xl border border-ink-200 px-4 py-3" /></label>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">E-mail de contact<input name="email" type="email" defaultValue={identity.email ?? ''} className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label><label className="text-sm font-medium">Téléphone<input name="phone" type="tel" className="mt-2 w-full rounded-xl border border-ink-200 px-4 py-3" /></label></div>
    <fieldset className="rounded-2xl border border-reunion-blue/20 bg-reunion-blue/[0.04] p-5"><label className="flex items-start gap-3"><input name="registration_enabled" type="checkbox" className="mt-1" /><span><span className="block font-semibold">Activer les inscriptions officielles</span><span className="mt-1 block text-xs leading-5 text-ink-500">Les joueurs devront être connectés pour inscrire leur équipe.</span></span></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Date limite<input name="registration_deadline" type="datetime-local" className="mt-2 w-full rounded-xl border border-reunion-blue/20 bg-white px-4 py-3" /></label><label className="text-sm font-medium">Équipes maximum<input name="max_teams" type="number" min={1} className="mt-2 w-full rounded-xl border border-reunion-blue/20 bg-white px-4 py-3" /></label></div></fieldset>
    <PendingSubmitButton pendingLabel="Création en cours…" className="w-full rounded-xl bg-ink-950 px-5 py-3.5 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">Publier le tournoi</PendingSubmitButton>
  </form></div></div></section>;
}
