import AdminPageHeader from '@/components/admin/AdminPageHeader';
import AuthNotice from '@/components/auth/AuthNotice';
import { requireAdmin } from '@/lib/auth';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { updateRegistrationStatus } from '../actions';

export default async function AdminRegistrationsPage({ searchParams }: { searchParams: Promise<{ erreur?: string }> }) {
  const [, params] = await Promise.all([requireAdmin(), searchParams]); const supabase = await createServerSupabaseClient();
  const { data, error } = await supabase.from('tournament_registrations').select('id, team_name, referent_email, referent_phone, status, created_at, tournament:tournaments(name)').order('created_at', { ascending: false }).limit(100);
  return <section className="px-4 py-10"><div className="mx-auto max-w-7xl"><AdminPageHeader eyebrow="Administration" title="Inscriptions" description="Vue support des inscriptions officielles. Les associations gardent la gestion quotidienne." /><AuthNotice error={params.erreur ?? error?.message} /><div className="mt-7 overflow-x-auto rounded-2xl border border-ink-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-ink-50 text-xs uppercase text-ink-400"><tr><th className="px-5 py-4">Tournoi</th><th className="px-5 py-4">Équipe</th><th className="px-5 py-4">Contact</th><th className="px-5 py-4">Statut</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-ink-100">{data?.map((registration) => { const tournament = Array.isArray(registration.tournament) ? registration.tournament[0] : registration.tournament; return <tr key={registration.id}><td className="px-5 py-4">{tournament?.name}</td><td className="px-5 py-4 font-semibold">{registration.team_name}</td><td className="px-5 py-4"><p>{registration.referent_email}</p><p className="text-xs text-ink-400">{registration.referent_phone}</p></td><td className="px-5 py-4">{registration.status}</td><td className="px-5 py-4"><form action={updateRegistrationStatus} className="flex gap-1"><input type="hidden" name="registration_id" value={registration.id} />{['confirmed','waitlisted','cancelled'].map((status) => <button key={status} name="status" value={status} className="rounded-lg border border-ink-200 px-2.5 py-2 text-[11px]">{status}</button>)}</form></td></tr>; })}</tbody></table>{!data?.length && <p className="p-8 text-center text-sm text-ink-500">Aucune inscription.</p>}</div></div></section>;
}
